title: Ready to Take Off
description: Ryan's personal website
theme: just-the-docs

url: https://ryankwon.dev

aux_links:
  GitHub: https://github.com/ryankwondev
  Twitter: https://twitter.com/ryankwondev
  Instagram: https://instagram.com/ryankwondev

include:
  - _sass/custom/custom.css